In [2]:
import numpy as np
import pandas as pd

In [3]:
DATAPATH = "/Users/misham/Desktop/data/cmi_sensor_data/cmi-detect-behavior-with-sensor-data/"

In [4]:
train_df = pd.read_csv(DATAPATH + "train.csv")
test_df = pd.read_csv(DATAPATH + "test.csv")
train_demo_df = pd.read_csv(DATAPATH + "train_demographics.csv")
test_demo_df = pd.read_csv(DATAPATH + "test_demographics.csv")

In [8]:
target_feature = "gesture"
train_only_features = ['gesture', 'sequence_type', 'orientation']

In [9]:
train_df.head(2)

,row_id,sequence_type,sequence_id,sequence_counter,subject,orientation,behavior,phase,gesture,acc_x,...,tof_5_v54,tof_5_v55,tof_5_v56,tof_5_v57,tof_5_v58,tof_5_v59,tof_5_v60,tof_5_v61,tof_5_v62,tof_5_v63
0,SEQ_000007_000000,Target,SEQ_000007,0,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,6.683594,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,SEQ_000007_000001,Target,SEQ_000007,1,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,6.949219,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [10]:
train_demo_df.head(2)

,subject,adult_child,age,sex,handedness,height_cm,shoulder_to_wrist_cm,elbow_to_wrist_cm
0,SUBJ_000206,1,41,1,1,172.0,50,25.0
1,SUBJ_001430,0,11,0,1,167.0,51,27.0

In [26]:
nan_counts = train_df.isna().sum()
features_with_na = nan_counts[nan_counts > 0]
print(features_with_na)

rot_w         3692
rot_x         3692
rot_y         3692
rot_z         3692
thm_1         6987
             ...
tof_5_v59    30142
tof_5_v60    30142
tof_5_v61    30142
tof_5_v62    30142
tof_5_v63    30142
Length: 329, dtype: int64

## Dealing with missing Data
Try:
- MissingIndicator to try and see if the model can pick up the meaning of missing values
- KNNImputer to fill missing values
- Think through each feature and trying to see what the missing values could mean.

### Missing Imputer

In [20]:
from sklearn.impute import MissingIndicator

In [27]:
indicator = MissingIndicator()

In [28]:
train_df = indicator.fit_transform(train_df)

In [30]:
train_df

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [29]:
nan_counts = train_df.isna().sum()
features_with_na = nan_counts[nan_counts > 0]
print(features_with_na)

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

### KNN Imputer